name: Deploy Quartz to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22 + npm 10.9.2
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true
          cache: 'npm'
      - run: |
        corepack enable
        corepack prepare npm@10.9.2 --activate
        node -v
        npm -v

      # --- 调试：构建前确认仓库里就有 static/i18n.js ---
      - name: Show repo tree before build (debug)
        run: |
          echo "== repo root =="
          ls -la
          echo "== static dir (should contain i18n.js) =="
          ls -la static || true
          echo "== tracked i18n files =="
          git ls-files | grep -i i18n || true

      - name: Install deps
        run: npm ci

      - name: Build Quartz (production)
        env:
          NODE_ENV: production
        run: npx quartz build

      # --- 兜底：若 Quartz 没拷贝 static，则手动复制 ---
      - name: Ensure static copied into public/static (fallback)
        run: |
          mkdir -p public/static
          # -r: 递归, -v: 输出日志, -u: 仅当源更新时覆盖
          cp -rvu static/* public/static/ 2>/dev/null || true

      # --- 调试：构建后列出 public 里的内容，确认 i18n.js 到位 ---
      - name: Show build tree after copy (debug)
        run: |
          echo "== expect: public/static/i18n.js =="
          find public -maxdepth 3 -type f -print | sed -n '1,200p'
          test -f public/static/i18n.js && echo "✅ Found public/static/i18n.js" || (echo "❌ STILL MISSING public/static/i18n.js" && exit 1)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
